# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - ./mysql-dump:/docker-entrypoint-initdb.d
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    #          --default-authentication-plugin=mysql_native_password
    #          --init-file /docker-entrypoint-initdb.d/init.sql  #attention here
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - "8095:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
  moodle:
    build:
      context: .
      dockerfile: .DockerFile
    image: moodle_bitnami
    ports:
      - '83:8080'
      - '447:8443'
    environment:
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=Password12345
      - MOODLE_EMAIL=user@example.com
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASSWORD=your_password
      - SMTP_PROTOCOL=tls
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - './moodle/local:/bitnami/moodle/local'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local