<?php

/**
 * @package    iic_service
 */

// We defined the web service functions to install.
$functions = array(
        'iic_service_hello_world' => array(
                'classname'   => 'iic_service_external',
                'methodname'  => 'hello_world',
                'classpath'   => 'local/iic_service/externallib.php',
                'description' => 'Return Hello World FIRSTNAME. Can change the text (Hello World) sending a new text as parameter',
                'type'        => 'read',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_update_coursesection' => array(
                'classname'   => 'iic_service_course_functions',
                'methodname'  => 'update_coursesection',
                'classpath'   => 'local/iic_service/course/lib.php',
                'description' => 'updates course section',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ), 
        'iic_service_get_course_format_options' => array(
                'classname'   => 'iic_service_course_functions',
                'methodname'  => 'get_course_format_options',
                'classpath'   => 'local/iic_service/course/lib.php',
                'description' => 'gets course format options',
                'type'        => 'read',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_uploadfile' => array(
                'classname'   => 'iic_service_course_functions',
                'methodname'  => 'uploadfile',
                'classpath'   => 'local/iic_service/course/lib.php',
                'description' => 'Upload file',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_createassignment' => array(
                'classname'   => 'iic_service_assign_functions',
                'methodname'  => 'create_assignment',
                'classpath'   => 'local/iic_service/mod/assign/lib.php',
                'description' => 'create assignment',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_updateassignment' => array(
                'classname'   => 'iic_service_assign_functions',
                'methodname'  => 'update_assignment',
                'classpath'   => 'local/iic_service/mod/assign/lib.php',
                'description' => 'update assignment',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ), 
        'iic_service_create_chat' => array(
                'classname'   => 'iic_service_chat_functions',
                'methodname'  => 'create_chat',
                'classpath'   => 'local/iic_service/mod/chat/lib.php',
                'description' => 'create chat',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_wiki' => array(
                'classname'   => 'iic_service_wiki_functions',
                'methodname'  => 'create_wiki',
                'classpath'   => 'local/iic_service/mod/wiki/lib.php',
                'description' => 'create wiki',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),  
        'iic_service_create_forum' => array(
                'classname'   => 'iic_service_forum_functions',
                'methodname'  => 'create_forum',
                'classpath'   => 'local/iic_service/mod/forum/lib.php',
                'description' => 'create forum',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),    
        'iic_service_update_forum' => array(
                'classname'   => 'iic_service_forum_functions',
                'methodname'  => 'update_forum',
                'classpath'   => 'local/iic_service/mod/forum/lib.php',
                'description' => 'update forum',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),         
        'iic_service_create_quiz' => array(
                'classname'   => 'iic_service_quiz_functions',
                'methodname'  => 'create_quiz',
                'classpath'   => 'local/iic_service/mod/quiz/lib.php',
                'description' => 'create quiz',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_create_quiz_and_questions' => array(
                'classname'   => 'iic_service_quiz_functions',
                'methodname'  => 'create_quiz_and_questions',
                'classpath'   => 'local/iic_service/mod/quiz/lib.php',
                'description' => 'create quiz and questions',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_update_quiz' => array(
                'classname'   => 'iic_service_quiz_functions',
                'methodname'  => 'update_quiz',
                'classpath'   => 'local/iic_service/mod/quiz/lib.php',
                'description' => 'update quiz',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_survey' => array(
                'classname'   => 'iic_service_survey_functions',
                'methodname'  => 'create_survey',
                'classpath'   => 'local/iic_service/mod/survey/lib.php',
                'description' => 'create survey',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_get_questionsfromcategory' => array(
                'classname'   => 'iic_service_quiz_functions',
                'methodname'  => 'get_questionsfromcategory',
                'classpath'   => 'local/iic_service/mod/quiz/lib.php',
                'description' => 'get questions from category',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_get_answersforquestion' => array(
                'classname'   => 'iic_service_quiz_functions',
                'methodname'  => 'get_answersforquestion',
                'classpath'   => 'local/iic_service/mod/quiz/lib.php',
                'description' => 'get answers for question',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_folder' => array(
                'classname'   => 'iic_service_folder_functions',
                'methodname'  => 'create_folder',
                'classpath'   => 'local/iic_service/mod/folder/lib.php',
                'description' => 'add new folder',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_update_folder' => array(
                'classname'   => 'iic_service_folder_functions',
                'methodname'  => 'update_folder',
                'classpath'   => 'local/iic_service/mod/folder/lib.php',
                'description' => 'update folder',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),   
        'iic_service_uploadfiletofolder' => array(
                'classname'   => 'iic_service_folder_functions',
                'methodname'  => 'uploadfiletofolder',
                'classpath'   => 'local/iic_service/mod/folder/lib.php',
                'description' => 'upload files to folder',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),             
        'iic_service_get_moduleid' => array(
                'classname'   => 'iic_service_module_functions',
                'methodname'  => 'get_moduleid',
                'classpath'   => 'local/iic_service/mod/lib.php',
                'description' => 'get module id',
                'type'        => 'read',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_get_allmodules' => array(
                'classname'   => 'iic_service_module_functions',
                'methodname'  => 'get_allmodules',
                'classpath'   => 'local/iic_service/mod/lib.php',
                'description' => 'get all modules',
                'type'        => 'read',
                'services'    => array('IIC_SERVICE'),
        ),             
        'iic_service_create_scormpackage' => array(
                'classname'   => 'iic_service_scorm_functions',
                'methodname'  => 'create_scormpackage',
                'classpath'   => 'local/iic_service/mod/scorm/lib.php',
                'description' => 'create scormpackage',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_page' => array(
                'classname'   => 'iic_service_page_functions',
                'methodname'  => 'create_page',
                'classpath'   => 'local/iic_service/mod/page/lib.php',
                'description' => 'create page',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_update_page' => array(
                'classname'   => 'iic_service_page_functions',
                'methodname'  => 'update_page',
                'classpath'   => 'local/iic_service/mod/page/lib.php',
                'description' => 'update page',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),  
        'iic_service_get_book' => array(
                'classname'   => 'iic_service_book_functions',
                'methodname'  => 'get_book',
                'classpath'   => 'local/iic_service/mod/book/lib.php',
                'description' => 'get book with chapter',
                'type'        => 'read',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_get_booksfromcourse' => array(
                'classname'   => 'iic_service_book_functions',
                'methodname'  => 'get_booksfromcourse',
                'classpath'   => 'local/iic_service/mod/book/lib.php',
                'description' => 'get all books from course',
                'type'        => 'read',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_add_gradecategory' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'add_gradecategory',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'add grade category',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),  
        'iic_service_update_gradecategory' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'update_gradecategory',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'update grade category',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ), 
        'iic_service_delete_gradecategory' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'delete_gradecategory',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'delete grade category',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ), 
        'iic_service_add_gradeitem' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'add_gradeitem',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'add grade item',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_update_gradeitem' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'update_gradeitem',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'update grade item',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_delete_gradeitem' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'delete_gradeitem',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'delete grade item',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),  
        'iic_service_create_book' => array(
                'classname'   => 'iic_service_book_functions',
                'methodname'  => 'create_book',
                'classpath'   => 'local/iic_service/mod/book/lib.php',
                'description' => 'add new book',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_bookchapter' => array(
                'classname'   => 'iic_service_book_functions',
                'methodname'  => 'create_bookchapter',
                'classpath'   => 'local/iic_service/mod/book/lib.php',
                'description' => 'add new chapter',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_zoom' => array(
                'classname'   => 'iic_service_zoom_functions',
                'methodname'  => 'create_zoom',
                'classpath'   => 'local/iic_service/mod/zoom/lib.php',
                'description' => 'add new zoom meeting',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_update_zoom' => array(
                'classname'   => 'iic_service_zoom_functions',
                'methodname'  => 'update_zoom',
                'classpath'   => 'local/iic_service/mod/zoom/lib.php',
                'description' => 'update zoom meeting',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_create_url' => array(
                'classname'   => 'iic_service_url_functions',
                'methodname'  => 'create_url',
                'classpath'   => 'local/iic_service/mod/url/lib.php',
                'description' => 'add new url',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_update_url' => array(
                'classname'   => 'iic_service_url_functions',
                'methodname'  => 'update_url',
                'classpath'   => 'local/iic_service/mod/url/lib.php',
                'description' => 'update url',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),   
        'iic_service_create_glossary' => array(
                'classname'   => 'iic_service_glossary_functions',
                'methodname'  => 'create_glossary',
                'classpath'   => 'local/iic_service/mod/glossary/lib.php',
                'description' => 'add new glossary',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),  
        'iic_service_update_glossary' => array(
                'classname'   => 'iic_service_glossary_functions',
                'methodname'  => 'update_glossary',
                'classpath'   => 'local/iic_service/mod/glossary/lib.php',
                'description' => 'update glossary',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),  
        'iic_service_create_label' => array(
                'classname'   => 'iic_service_label_functions',
                'methodname'  => 'create_label',
                'classpath'   => 'local/iic_service/mod/label/lib.php',
                'description' => 'add new label',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_update_label' => array(
                'classname'   => 'iic_service_label_functions',
                'methodname'  => 'update_label',
                'classpath'   => 'local/iic_service/mod/label/lib.php',
                'description' => 'update label',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ), 
        'iic_service_backup_label' => array(
                'classname'   => 'iic_service_label_functions',
                'methodname'  => 'get_label_backup',
                'classpath'   => 'local/iic_service/mod/label/lib.php',
                'description' => 'get label backup',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_backup_module' => array(
                'classname'   => 'iic_service_backup_functions',
                'methodname'  => 'backup_module',
                'classpath'   => 'local/iic_service/mod/backup/lib.php',
                'description' => 'backup module',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_restore_module' => array(
                'classname'   => 'iic_service_backup_functions',
                'methodname'  => 'restore_module',
                'classpath'   => 'local/iic_service/mod/backup/lib.php',
                'description' => 'restore module',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_backup_course' => array(
                'classname'   => 'iic_service_course_functions',
                'methodname'  => 'backup_course',
                'classpath'   => 'local/iic_service/course/lib.php',
                'description' => 'backup course',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_restore_course' => array(
                'classname'   => 'iic_service_course_functions',
                'methodname'  => 'restore_course',
                'classpath'   => 'local/iic_service/course/lib.php',
                'description' => 'restore course',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_get_gradebook' => array(
                'classname'   => 'iic_service_grade_functions',
                'methodname'  => 'get_gradebook',
                'classpath'   => 'local/iic_service/mod/grade/lib.php',
                'description' => 'get gradebook',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),     
        'iic_service_create_attachment' => array(
                'classname'   => 'iic_service_file_functions',
                'methodname'  => 'create_attachment',
                'classpath'   => 'local/iic_service/mod/file/lib.php',
                'description' => 'create attachment',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_delete_attachment' => array(
                'classname'   => 'iic_service_file_functions',
                'methodname'  => 'delete_attachment',
                'classpath'   => 'local/iic_service/mod/file/lib.php',
                'description' => 'delete attachment',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_create_role' => array(
                'classname'   => 'iic_service_role_functions',
                'methodname'  => 'create_role',
                'classpath'   => 'local/iic_service/role/lib.php',
                'description' => 'create role',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_delete_role' => array(
                'classname'   => 'iic_service_role_functions',
                'methodname'  => 'delete_role',
                'classpath'   => 'local/iic_service/role/lib.php',
                'description' => 'delete role',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_add_role_capabilities' => array(
                'classname'   => 'iic_service_role_functions',
                'methodname'  => 'add_role_capabilities',
                'classpath'   => 'local/iic_service/role/lib.php',
                'description' => 'add role capabilities',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        ),
        'iic_service_Get_PluginVersion' => array(
                'classname'   => 'iic_service_course_functions',
                'methodname'  => 'Get_Plugin_Version',
                'classpath'   => 'local/iic_service/course/lib.php',
                'description' => 'Gets Plugin version',
                'type'        => 'write',
                'services'    => array('IIC_SERVICE'),
        )
);

// We define the services to install as pre-build services. A pre-build service is not editable by administrator.
$services = array(
        'IIC service' => array(
                'functions' => array (),
                'restrictedusers' => 0,
                'shortname' => 'IIC_SERVICE',
                'enabled'=>1,
                'downloadfiles' => 1,
                'uploadfiles' => 1
        )
);
